name: tcs_dff_network
description: Digital foundation framework for developing flutter apps
version: 0.1.0
homepage: https://gitlabyono2.bank.sbi/yono2-0/frontend/flutter/tcs_dff_flutter.git
publish_to: none
environment:
  sdk: 3.2.3
  flutter: '>=3.16.5'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  tcs_dff_types:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_types/
  tcs_dff_device_feature:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_device_feature/
  tcs_dff_cipher:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_cipher/
  tcs_dff_storage:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_storage/
  tcs_dff_shared_library:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_shared_library/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1
  tcs_dff_test: ^0.1.0
dependency_overrides:
  tcs_dff_types:
    path: ../tcs_dff_types
  tcs_dff_cipher:
    path: ../../packages/tcs_dff_cipher
  tcs_dff_test:
    path: ../../packages/tcs_dff_test
  tcs_dff_storage:
    path: ../tcs_dff_storage
  tcs_dff_device_feature:
    path: ../tcs_dff_device_feature
  tcs_dff_shared_library:
    path: ../tcs_dff_shared_library
flutter: 
