name: tcs_dff_security
description: Digital foundation framework for developing flutter apps
version: 0.1.0
homepage: https://gitlabyono2.bank.sbi/yono2-0/frontend/flutter/tcs_dff_flutter.git
publish_to: none
environment:
  sdk: 3.2.3
  flutter: '>=3.16.5'
dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  vpn_connection_detector: ^1.0.6
  package_info_plus: ^5.0.1
  native_flutter_proxy: ^0.1.15
  tcs_dff_types:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_types/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
dependency_overrides:
  tcs_dff_types:
    path: ../tcs_dff_types
flutter:
  plugin:
    platforms:
      android:
        package: com.dff.security
        pluginClass: TcsDffSecurityPlugin
      ios:
        pluginClass: TcsDffSecurityPlugin
