name: shared
description: Digital foundation framework for developing flutter apps
publish_to: none
version: 0.1.0
environment:
  sdk: 3.2.3
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  tcs_dff_types:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_types/
  tcs_dff_shared_library:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_shared_library/
  tcs_dff_device_feature:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_device_feature/
  tcs_dff_route:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_route/
  intl: any
  tcs_dff_network:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_network/
  tcs_dff_core:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_core/
  tcs_dff_di:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_di/
  tcs_dff_cipher:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_cipher/
  tcs_dff_design_system:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_design_system/
  tcs_dff_storage:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_storage/
  tcs_dff_security:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_security/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
dependency_overrides:
  tcs_dff_design_system:
    path: ../../packages/tcs_dff_design_system
flutter:
  uses-material-design: true
  generate: true
  assets: [lib/resource/strings/]
homepage: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
