name: tcs_dff_tools
description: Digital foundation framework for developing flutter apps
version: 0.1.0
homepage: https://gitlabyono2.bank.sbi/yono2-0/frontend/flutter/tcs_dff_flutter.git
publish_to: none
executables:
  codegen: 
  pub_manager: 
environment:
  sdk: 3.2.3
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  yaml: ^3.1.2
  path: ^1.8.3
  args: ^2.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
flutter: 
