name: tcs_dff_test
description: Digital foundation framework for developing flutter apps
version: 0.1.0
homepage: https://gitlabyono2.bank.sbi/yono2-0/frontend/flutter/tcs_dff_flutter.git
publish_to: none
environment:
  sdk: 3.2.3
  flutter: '>=3.16.5'
dependencies:
  flutter:
    sdk: flutter
  mocktail: ^1.0.1
  tcs_dff_types:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_types/
  tcs_dff_network:
    git:
      url: http://10.10.245.133:443/tcs_sbi_yono/tcs_dff_flutter.git
      ref: main
      path: packages/tcs_dff_network/
dependency_overrides:
  tcs_dff_types:
    path: ../../packages/tcs_dff_types
  tcs_dff_network:
    path: ../tcs_dff_network
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
